@extends('backend.layouts.master')

@section('title', 'Manajemen Survey Kepuasan Masyarakat')

@push('css')
    <style>
        .main-content {
            padding-top: 100px !important;
        }

        .page-content {
            margin-top: -4rem !important;
        }

        .page-title-box {
            background: linear-gradient(135deg, #556ee6 0%, #364574 100%) !important;
            color: white !important;
            padding: 1.8rem 1.5rem !important;
            border-radius: 10px;
        }

        .card-modern {
            border: none;
            border-radius: 12px;
            box-shadow: 0 8px 30px rgba(0, 0, 0, 0.1) !important;
        }

        .card-header-modern {
            background: linear-gradient(135deg, #556ee6 0%, #364574 100%) !important;
            color: white !important;
            border-bottom: none;
            padding: 1.4rem 1.5rem !important;
        }

        .triwulan-card {
            transition: all 0.3s ease;
            border: 2px solid transparent;
            height: 100%;
        }

        .triwulan-card:hover {
            transform: translateY(-5px);
            box-shadow: 0 10px 25px rgba(85, 110, 230, 0.25) !important;
        }

        .triwulan-card.active {
            border-color: #556ee6;
            background-color: #f8f9ff;
        }

        .indikator-value {
            font-size: 1.1rem;
            font-weight: 600;
            color: #364574;
        }

        .grade-badge {
            font-size: 0.95rem;
            padding: 6px 14px;
            border-radius: 30px;
            font-weight: 500;
        }

        .info-box {
            background: linear-gradient(135deg, #f8f9ff, #eef2ff);
            border-left: 5px solid #556ee6;
            border-radius: 8px;
        }

        .summary-card {
            transition: all 0.3s ease;
        }
    </style>
@endpush

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="d-flex align-items-center justify-content-between">
                    <h4 class="mb-0 font-size-18 text-white">Manajemen Survey Kepuasan Masyarakat</h4>
                    <div class="page-title-right">
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item"><a href="{{ route('backend.index') }}">Dashboard</a></li>
                            <li class="breadcrumb-item active">Survey</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-3">
        <div class="col-12">
            <div class="card card-modern">
                <div class="card-header card-header-modern d-flex justify-content-between align-items-center">
                    <h4 class="card-title mb-0 text-white">Data Survey Kepuasan Masyarakat</h4>
                    <a href="{{ route('backend.survey.create') }}" class="btn btn-light btn-add-banner">
                        <i class="mdi mdi-plus me-1"></i> Tambah Data Baru
                    </a>
                </div>

                <div class="card-body p-4">
                    <!-- Pilih Tahun -->
                    <div class="mb-4">
                        <label class="form-label fw-semibold">Pilih Tahun</label>
                        <select id="select-year" class="form-select form-select-lg">
                            <option value="">-- Pilih Tahun --</option>
                            @foreach($availableYears as $year)
                                <option value="{{ $year }}">{{ $year }}</option>
                            @endforeach
                        </select>
                    </div>

                    <!-- Ringkasan Tahunan -->
                    <div id="year-summary" class="row g-3 mb-4" style="display: none;">
                        <!-- Generated by JS -->
                    </div>

                    <!-- Daftar Triwulan -->
                    <div id="triwulan-list" class="row g-3" style="display: none;">
                        <!-- Generated by JS -->
                    </div>

                    <!-- Detail Panel -->
                    <div id="detail-panel" class="mt-4" style="display: none;">
                        <div class="info-box p-4 rounded-3">
                            <div class="d-flex justify-content-between align-items-center mb-4">
                                <h5 id="detail-title" class="mb-0"></h5>
                                <div>
                                    <a id="btn-edit" href="#" class="btn btn-warning btn-sm me-2">
                                        <i class="mdi mdi-pencil"></i> Edit
                                    </a>
                                    <button id="btn-delete" class="btn btn-danger btn-sm">
                                        <i class="mdi mdi-delete"></i> Hapus
                                    </button>
                                </div>
                            </div>

                            <div class="row g-4">
                                <div class="col-md-5">
                                    <h6 class="mb-4 text-muted fw-semibold">Jumlah Responden</h6>
                                    <div class="d-flex align-items-center mb-4">
                                        <div class="flex-shrink-0 bg-primary bg-opacity-10 rounded-3 p-3">
                                            <i class="mdi mdi-human-male fs-1 text-primary"></i>
                                        </div>
                                        <div class="flex-grow-1 ms-3">
                                            <span class="text-muted small d-block">Laki-laki</span>
                                            <span id="jumlah-laki" class="fs-2 fw-bold text-primary"></span>
                                            <span class="text-muted ms-1">orang</span>
                                        </div>
                                    </div>
                                    <div class="d-flex align-items-center mb-4">
                                        <div class="flex-shrink-0 bg-danger bg-opacity-10 rounded-3 p-3">
                                            <i class="mdi mdi-human-female fs-1 text-danger"></i>
                                        </div>
                                        <div class="flex-grow-1 ms-3">
                                            <span class="text-muted small d-block">Perempuan</span>
                                            <span id="jumlah-perempuan" class="fs-2 fw-bold text-danger"></span>
                                            <span class="text-muted ms-1">orang</span>
                                        </div>
                                    </div>
                                    <div class="d-flex align-items-center pt-3 border-top">
                                        <div class="flex-shrink-0 bg-success bg-opacity-10 rounded-3 p-3">
                                            <i class="mdi mdi-account-group fs-1 text-success"></i>
                                        </div>
                                        <div class="flex-grow-1 ms-3">
                                            <span class="text-muted small d-block">Total Responden</span>
                                            <span id="total-responden" class="fs-2 fw-bold text-success"></span>
                                            <span class="text-muted ms-1">orang</span>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-7">
                                    <h6 class="mb-3">Nilai 9 Indikator</h6>
                                    <div id="indikator-list" class="row g-3"></div>

                                    <div class="mt-4 pt-4 border-top">
                                        <div class="d-flex justify-content-between align-items-end">
                                            <div>
                                                <strong class="d-block mb-1">Indeks Kepuasan Masyarakat (IKM)</strong>
                                                <span id="rata-rata" class="fs-2 fw-bold text-success"></span>
                                            </div>
                                            <div id="grade-badge" class="text-end"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('script')
    <script>
        // ==================== SWEETALERT SUCCESS ====================
        @if (session('success'))
            Swal.fire({
                icon: 'success',
                title: 'Berhasil!',
                text: '{{ session('success') }}',
                toast: true,
                position: 'top-end',
                timer: 3000,
                showConfirmButton: false,
                timerProgressBar: true
            });
        @endif
    </script>
    <script>
        let surveyData = @json($grouped);
        let currentYear = null;
        let currentTriwulan = null;
        let currentSurveyId = null;

        const triwulanList = [
            { num: 1, nama: 'Triwulan 1 (Jan-Mar)' },
            { num: 2, nama: 'Triwulan 2 (Apr-Jun)' },
            { num: 3, nama: 'Triwulan 3 (Jul-Sep)' },
            { num: 4, nama: 'Triwulan 4 (Okt-Des)' }
        ];

        function getGrade(nilai) {
            if (nilai >= 3.53) return { text: 'Sangat Baik', color: 'bg-success' };
            if (nilai >= 3.06) return { text: 'Baik', color: 'bg-primary' };
            if (nilai >= 2.60) return { text: 'Kurang Baik', color: 'bg-warning' };
            return { text: 'Tidak Baik', color: 'bg-danger' };
        }

        // ==================== RINGKASAN TAHUNAN ====================
        function renderYearSummary(year) {
            const yearData = surveyData[year];
            if (!yearData) return;

            let totalLaki = 0, totalPerempuan = 0, totalIndikator = 0, totalDataPoints = 0;

            Object.keys(yearData).forEach(tw => {
                const data = yearData[tw];
                totalLaki += Number(data.jumlah_laki || 0);
                totalPerempuan += Number(data.jumlah_perempuan || 0);

                for (let i = 1; i <= 9; i++) {
                    const val = parseFloat(data[`indikator${i}`]) || 0;
                    totalIndikator += val;
                    totalDataPoints++;
                }
            });

            const totalResponden = totalLaki + totalPerempuan;
            const rataRataIKM = totalDataPoints > 0 ? (totalIndikator / totalDataPoints).toFixed(2) : '0.00';
            const grade = getGrade(parseFloat(rataRataIKM));

            const html = `
                                <div class="col-md-3">
                                    <div class="card summary-card text-center p-4 h-100">
                                        <div class="mx-auto bg-primary bg-opacity-10 rounded-3 p-3 mb-3" style="width:70px;height:70px;display:flex;align-items:center;justify-content:center;">
                                            <i class="mdi mdi-human-male fs-1 text-primary"></i>
                                        </div>
                                        <h6 class="text-muted mb-2">Laki-laki</h6>
                                        <span class="fs-3 fw-bold text-primary">${totalLaki.toLocaleString('id-ID')}</span>
                                        <small class="text-muted">orang</small>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="card summary-card text-center p-4 h-100">
                                        <div class="mx-auto bg-danger bg-opacity-10 rounded-3 p-3 mb-3" style="width:70px;height:70px;display:flex;align-items:center;justify-content:center;">
                                            <i class="mdi mdi-human-female fs-1 text-danger"></i>
                                        </div>
                                        <h6 class="text-muted mb-2">Perempuan</h6>
                                        <span class="fs-3 fw-bold text-danger">${totalPerempuan.toLocaleString('id-ID')}</span>
                                        <small class="text-muted">orang</small>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="card summary-card text-center p-4 h-100">
                                        <div class="mx-auto bg-success bg-opacity-10 rounded-3 p-3 mb-3" style="width:70px;height:70px;display:flex;align-items:center;justify-content:center;">
                                            <i class="mdi mdi-account-group fs-1 text-success"></i>
                                        </div>
                                        <h6 class="text-muted mb-2">Total Responden</h6>
                                        <span class="fs-3 fw-bold text-success">${totalResponden.toLocaleString('id-ID')}</span>
                                        <small class="text-muted">orang</small>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="card summary-card text-center p-4 h-100" style="background: linear-gradient(135deg, #f8f9ff, #eef2ff);">
                                        <h6 class="text-muted mb-3">IKM Tahun ${year}</h6>
                                        <span class="fs-3 fw-bold text-success d-block mb-2">${rataRataIKM}</span>
                                        <span class="badge ${grade.color} grade-badge px-3 py-2 fs-6">${grade.text}</span>
                                    </div>
                                </div>
                            `;

            document.getElementById('year-summary').innerHTML = html;
            document.getElementById('year-summary').style.display = 'flex';
        }

        // ==================== RENDER TRI WULAN ====================
        function renderTriwulanCards(year) {
            const container = document.getElementById('triwulan-list');
            container.innerHTML = '';

            triwulanList.forEach(tw => {
                const hasData = surveyData[year] && surveyData[year][tw.num] !== undefined;

                const cardHTML = `
                                    <div class="col-md-3">
                                        <div class="card triwulan-card h-100 text-center ${hasData ? 'border-primary' : ''}" 
                                             style="cursor:pointer;" data-triwulan="${tw.num}">
                                            <div class="card-body py-4">
                                                <h5 class="mb-1">Triwulan ${tw.num}</h5>
                                                <p class="mb-0 text-muted small">${tw.nama}</p>
                                                ${hasData ?
                        `<span class="badge bg-success mt-2">Ada Data</span>` :
                        `<span class="badge bg-secondary mt-2">Belum Ada</span>`
                    }
                                            </div>
                                        </div>
                                    </div>`;
                container.insertAdjacentHTML('beforeend', cardHTML);
            });

            container.style.display = 'flex';

            container.querySelectorAll('.triwulan-card').forEach(card => {
                card.addEventListener('click', function () {
                    document.querySelectorAll('.triwulan-card').forEach(c => c.classList.remove('active'));
                    this.classList.add('active');

                    currentTriwulan = parseInt(this.dataset.triwulan);
                    showDetail(currentTriwulan);
                });
            });
        }

        function showDetail(triwulan) {
            const yearData = surveyData[currentYear];
            const data = yearData ? yearData[triwulan] : null;
            const panel = document.getElementById('detail-panel');

            if (!data) {
                Swal.fire({
                    title: 'Data belum tersedia',
                    text: `Apakah Anda ingin menambahkan data untuk Triwulan ${triwulan}?`,
                    icon: 'info',
                    showCancelButton: true,
                    confirmButtonText: 'Tambah Sekarang'
                }).then(res => {
                    if (res.isConfirmed) {
                        window.location.href = `{{ route('backend.survey.create') }}?year=${currentYear}&triwulan=${triwulan}`;
                    }
                });
                return;
            }

            currentSurveyId = data.id;

            let sum = 0;
            let indikatorHtml = '';
            const indikators = ['indikator1', 'indikator2', 'indikator3', 'indikator4', 'indikator5', 'indikator6', 'indikator7', 'indikator8', 'indikator9'];
            const labels = ['Persyaratan', 'Sistem, Mekanisme & Prosedur', 'Waktu Penyelesaian', 'Biaya/Tarif', 'Produk/Spesifikasi', 'Kompetensi Pelaksana', 'Perilaku Pelaksana', 'Penanganan Pengaduan', 'Sarana & Prasarana'];

            indikators.forEach((key, i) => {
                const val = parseFloat(data[key]) || 0;
                sum += val;
                indikatorHtml += `
                                    <div class="col-6 col-sm-4 mb-2">
                                        <small class="text-muted">${labels[i]}</small><br>
                                        <span class="indikator-value">${val.toFixed(2)}</span>
                                    </div>`;
            });

            const rataRata = (sum / 9).toFixed(2);
            const grade = getGrade(parseFloat(rataRata));

            document.getElementById('detail-title').innerHTML = `Tahun <strong>${currentYear}</strong> — Triwulan ${triwulan}`;
            document.getElementById('jumlah-laki').textContent = Number(data.jumlah_laki || 0).toLocaleString('id-ID');
            document.getElementById('jumlah-perempuan').textContent = Number(data.jumlah_perempuan || 0).toLocaleString('id-ID');
            document.getElementById('total-responden').textContent = (Number(data.jumlah_laki || 0) + Number(data.jumlah_perempuan || 0)).toLocaleString('id-ID');

            document.getElementById('indikator-list').innerHTML = indikatorHtml;
            document.getElementById('rata-rata').textContent = rataRata;
            document.getElementById('grade-badge').innerHTML = `<span class="badge ${grade.color} grade-badge">${grade.text}</span>`;

            document.getElementById('btn-edit').href = `{{ route('backend.survey.edit', ':id') }}`.replace(':id', data.id);

            document.getElementById('detail-panel').style.display = 'block';
        }

        // Event ketika tahun dipilih
        document.getElementById('select-year').addEventListener('change', function () {
            currentYear = this.value;
            const triwulanListEl = document.getElementById('triwulan-list');
            const detailPanel = document.getElementById('detail-panel');

            detailPanel.style.display = 'none';

            if (!currentYear) {
                document.getElementById('year-summary').style.display = 'none';
                triwulanListEl.style.display = 'none';
                return;
            }

            renderYearSummary(currentYear);
            renderTriwulanCards(currentYear);
        });

        // Delete Button
        document.addEventListener('click', function (e) {
            if (e.target && e.target.id === 'btn-delete') {
                if (!currentSurveyId) return;

                Swal.fire({
                    title: 'Yakin ingin menghapus?',
                    text: "Data ini akan dihapus permanen!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#d33',
                    cancelButtonColor: '#3085d6',
                    confirmButtonText: 'Ya, Hapus!'
                }).then((result) => {
                    if (result.isConfirmed) {
                        fetch(`{{ route('backend.survey.destroy', ':id') }}`.replace(':id', currentSurveyId), {
                            method: 'DELETE',
                            headers: { 'X-CSRF-TOKEN': '{{ csrf_token() }}' }
                        }).then(() => {
                            Swal.fire('Terhapus!', 'Data survey berhasil dihapus.', 'success')
                                .then(() => location.reload());
                        });
                    }
                });
            }
        });
    </script>
@endpush