@extends('backend.layouts.master')

@section('title', 'Manajemen Perizinan Terbit')

@push('css')
    <style>
        .main-content {
            padding-top: 100px !important;
        }

        .page-content {
            margin-top: -4rem !important;
        }

        .page-title-box {
            background: linear-gradient(135deg, #556ee6 0%, #364574 100%) !important;
            color: white !important;
            padding: 1.8rem 1.5rem !important;
            border-radius: 10px;
        }

        .card-modern {
            border: none;
            border-radius: 12px;
            box-shadow: 0 8px 30px rgba(0, 0, 0, 0.1) !important;
        }

        .card-header-modern {
            background: linear-gradient(135deg, #556ee6 0%, #364574 100%) !important;
            color: white !important;
            border-bottom: none;
            padding: 1.4rem 1.5rem !important;
        }

        .triwulan-card {
            transition: all 0.3s ease;
            border: 2px solid transparent;
            height: 100%;
            cursor: pointer;
        }

        .triwulan-card:hover {
            transform: translateY(-5px);
            box-shadow: 0 10px 25px rgba(85, 110, 230, 0.25) !important;
        }

        .triwulan-card.active {
            border-color: #556ee6;
            background-color: #f8f9ff;
        }

        .summary-card {
            transition: all 0.3s ease;
        }

        .summary-number {
            font-size: 1.8rem;
            font-weight: 700;
        }
    </style>
@endpush

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="d-flex align-items-center justify-content-between">
                    <h4 class="mb-0 font-size-18 text-white">Manajemen Perizinan Terbit</h4>
                    <div class="page-title-right">
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item"><a href="{{ route('backend.index') }}">Dashboard</a></li>
                            <li class="breadcrumb-item active">Perizinan Terbit</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-3">
        <div class="col-12">
            <div class="card card-modern">
                <div class="card-header card-header-modern d-flex justify-content-between align-items-center">
                    <h4 class="card-title mb-0 text-white">Data Perizinan Terbit</h4>
                    <a href="{{ route('backend.perizinan-terbit.create') }}" class="btn btn-light btn-add-banner">
                        <i class="mdi mdi-plus me-1"></i> Tambah Data Baru
                    </a>
                </div>

                <div class="card-body p-4">
                    <!-- Pilih Tahun -->
                    <div class="mb-4">
                        <label class="form-label fw-semibold">Pilih Tahun</label>
                        <select id="select-year" class="form-select form-select-lg">
                            <option value="">-- Pilih Tahun --</option>
                            @foreach($availableYears as $year)
                                <option value="{{ $year }}">{{ $year }}</option>
                            @endforeach
                        </select>
                    </div>

                    <!-- Ringkasan Tahunan -->
                    <div id="year-summary" class="row g-3 mb-4" style="display: none;">
                        <!-- Generated by JS -->
                    </div>

                    <!-- Daftar Triwulan -->
                    <div id="triwulan-list" class="row g-3" style="display: none;">
                        <!-- Generated by JS -->
                    </div>

                    <!-- Detail Panel -->
                    <div id="detail-panel" class="mt-4" style="display: none;">
                        <div class="info-box p-4 rounded-3">
                            <div class="d-flex justify-content-between align-items-center mb-4">
                                <h5 id="detail-title" class="mb-0"></h5>
                                <div>
                                    <a id="btn-edit" href="#" class="btn btn-warning btn-sm me-2">
                                        <i class="mdi mdi-pencil"></i> Edit
                                    </a>
                                    <button id="btn-delete" class="btn btn-danger btn-sm">
                                        <i class="mdi mdi-delete"></i> Hapus
                                    </button>
                                </div>
                            </div>

                            <div class="row g-4 text-center">
                                <div class="col-md-4">
                                    <strong class="text-muted d-block mb-1">OSS RBA</strong>
                                    <span id="oss_rba" class="fs-3 fw-bold text-primary"></span>
                                </div>
                                <div class="col-md-4">
                                    <strong class="text-muted d-block mb-1">SiCantik Cloud</strong>
                                    <span id="sicantik_cloud" class="fs-3 fw-bold text-info"></span>
                                </div>
                                <div class="col-md-4">
                                    <strong class="text-muted d-block mb-1">SIMBG</strong>
                                    <span id="simbg" class="fs-3 fw-bold text-success"></span>
                                </div>
                            </div>

                            <div class="mt-4 pt-4 border-top text-center">
                                <strong class="text-muted d-block mb-2">Total Perizinan Terbit</strong>
                                <span id="total_terbit" class="fs-4 fw-bold text-danger"></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('script')
    <script>
        // SweetAlert Success
        @if (session('success'))
            Swal.fire({
                icon: 'success',
                title: 'Berhasil!',
                text: '{{ session('success') }}',
                toast: true,
                position: 'top-end',
                timer: 3000,
                showConfirmButton: false
            });
        @endif
    </script>
    <script>
        let surveyData = @json($grouped);   // reuse variabel
        let currentYear = null;
        let currentTriwulan = null;
        let currentSurveyId = null;

        const triwulanList = [
            { num: 1, nama: 'Triwulan 1 (Jan-Mar)' },
            { num: 2, nama: 'Triwulan 2 (Apr-Jun)' },
            { num: 3, nama: 'Triwulan 3 (Jul-Sep)' },
            { num: 4, nama: 'Triwulan 4 (Okt-Des)' }
        ];

        function renderYearSummary(year) {
            const yearData = surveyData[year];
            if (!yearData) return;

            let totalOSS = 0, totalSicantik = 0, totalSIMBG = 0, totalTerbit = 0;

            Object.values(yearData).forEach(data => {
                totalOSS += Number(data.oss_rba || 0);
                totalSicantik += Number(data.sicantik_cloud || 0);
                totalSIMBG += Number(data.simbg || 0);
                totalTerbit += Number(data.total_terbit || 0);
            });

            const html = `
                            <div class="col-md-3">
                                <div class="card summary-card p-4 text-center">
                                    <h6 class="text-muted mb-2">OSS RBA</h6>
                                    <span class="summary-number text-primary">${totalOSS.toLocaleString('id-ID')}</span>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="card summary-card p-4 text-center">
                                    <h6 class="text-muted mb-2">SiCantik Cloud</h6>
                                    <span class="summary-number text-info">${totalSicantik.toLocaleString('id-ID')}</span>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="card summary-card p-4 text-center">
                                    <h6 class="text-muted mb-2">SIMBG</h6>
                                    <span class="summary-number text-success">${totalSIMBG.toLocaleString('id-ID')}</span>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="card summary-card p-4 text-center border-primary" style="background: linear-gradient(135deg, #f8f9ff, #eef2ff);">
                                    <h6 class="text-muted mb-2">Total Terbit Tahun ${year}</h6>
                                    <span class="summary-number text-danger">${totalTerbit.toLocaleString('id-ID')}</span>
                                </div>
                            </div>
                        `;

            document.getElementById('year-summary').innerHTML = html;
            document.getElementById('year-summary').style.display = 'flex';
        }

        function renderTriwulanCards(year) {
            const container = document.getElementById('triwulan-list');
            container.innerHTML = '';

            triwulanList.forEach(tw => {
                const hasData = surveyData[year] && surveyData[year][tw.num] !== undefined;

                const cardHTML = `
                                <div class="col-md-3">
                                    <div class="card triwulan-card h-100 text-center ${hasData ? 'border-primary' : ''}" 
                                         style="cursor:pointer;" data-triwulan="${tw.num}">
                                        <div class="card-body py-4">
                                            <h5 class="mb-1">TW ${tw.num}</h5>
                                            <p class="mb-0 text-muted small">${tw.nama}</p>
                                            ${hasData ?
                        `<span class="badge bg-success mt-2">Ada Data</span>` :
                        `<span class="badge bg-secondary mt-2">Belum Ada</span>`
                    }
                                        </div>
                                    </div>
                                </div>`;
                container.insertAdjacentHTML('beforeend', cardHTML);
            });

            container.style.display = 'flex';

            container.querySelectorAll('.triwulan-card').forEach(card => {
                card.addEventListener('click', function () {
                    document.querySelectorAll('.triwulan-card').forEach(c => c.classList.remove('active'));
                    this.classList.add('active');

                    currentTriwulan = parseInt(this.dataset.triwulan);
                    showDetail(currentTriwulan);
                });
            });
        }

        function showDetail(triwulan) {
            const yearData = surveyData[currentYear];
            const data = yearData ? yearData[triwulan] : null;
            const panel = document.getElementById('detail-panel');

            if (!data) {
                Swal.fire({
                    title: 'Data belum tersedia',
                    text: `Tambahkan data untuk Triwulan ${triwulan}?`,
                    icon: 'info',
                    showCancelButton: true,
                    confirmButtonText: 'Tambah Sekarang'
                }).then(res => {
                    if (res.isConfirmed) {
                        window.location.href = `{{ route('backend.perizinan-terbit.create') }}?year=${currentYear}&triwulan=${triwulan}`;
                    }
                });
                return;
            }

            currentSurveyId = data.id;

            document.getElementById('detail-title').innerHTML = `Tahun <strong>${currentYear}</strong> — Triwulan ${triwulan}`;
            document.getElementById('oss_rba').textContent = Number(data.oss_rba || 0).toLocaleString('id-ID');
            document.getElementById('sicantik_cloud').textContent = Number(data.sicantik_cloud || 0).toLocaleString('id-ID');
            document.getElementById('simbg').textContent = Number(data.simbg || 0).toLocaleString('id-ID');
            document.getElementById('total_terbit').textContent = Number(data.total_terbit || 0).toLocaleString('id-ID');

            document.getElementById('btn-edit').href = `{{ route('backend.perizinan-terbit.edit', ':id') }}`.replace(':id', data.id);

            panel.style.display = 'block';
        }

        // Event Pilih Tahun
        document.getElementById('select-year').addEventListener('change', function () {
            currentYear = this.value;
            const triwulanListEl = document.getElementById('triwulan-list');
            const detailPanel = document.getElementById('detail-panel');

            detailPanel.style.display = 'none';

            if (!currentYear) {
                document.getElementById('year-summary').style.display = 'none';
                triwulanListEl.style.display = 'none';
                return;
            }

            renderYearSummary(currentYear);
            renderTriwulanCards(currentYear);
        });

        // Delete Button
        document.addEventListener('click', function (e) {
            if (e.target && e.target.id === 'btn-delete') {
                if (!currentSurveyId) return;

                Swal.fire({
                    title: 'Yakin ingin menghapus?',
                    text: "Data ini akan dihapus permanen!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#d33',
                    cancelButtonColor: '#3085d6',
                    confirmButtonText: 'Ya, Hapus!'
                }).then((result) => {
                    if (result.isConfirmed) {
                        fetch(`{{ route('backend.perizinan-terbit.destroy', ':id') }}`.replace(':id', currentSurveyId), {
                            method: 'DELETE',
                            headers: { 'X-CSRF-TOKEN': '{{ csrf_token() }}' }
                        }).then(() => {
                            Swal.fire('Terhapus!', 'Data berhasil dihapus.', 'success')
                                .then(() => location.reload());
                        });
                    }
                });
            }
        });
    </script>
@endpush